Add "plane_crash"
MT-CTF/maps pull request #124
Opened 2020-10-09 14:11 UTC by JostP

(This pull request was generated by a script)

2020-10-09 14:18 UTC, JostP commented
Needs screenshot

2020-10-09 14:41 UTC, JostP commented
Map doesn't work. Bases' coordinates are wrong

2020-10-09 15:56 UTC, olliy1or commented
also needs a license

2020-11-05 07:19 UTC, Sirius-Black4 commented
I have licensed the latest map which is in the forums u can update it from there, plus u can see my latest post on the forums and that i have sent screenshots too.

2020-11-06 15:00 UTC, Avyukt1 commented
You need to select Z=0 while placing the barriers.
If you do X=0, you will get wrong initials of the bases and the barrier will be crashed.

2020-11-06 17:15 UTC, Sirius-Black4 commented
Avyukt 
i'm not sure if that's true because i think that its not the purpose of the x = 0 and z = 0,these are just the way the barrier is placed,if u put x = 0 the barrier will face a different direction and same if you put z = 0.

2020-11-06 17:16 UTC, Sirius-Black4 commented
Is there still some problems with the map or is it all fixed(?), if yes tell me how to fix it.

2020-11-07 01:03 UTC, Avyukt1 commented
@Sirius-Black4 I had got a lots of errors while making my map.

2020-11-07 08:45 UTC, Sirius-Black4 commented
Is there anything i can do to fix the coords?

2020-11-07 11:20 UTC, Avyukt1 commented
Lets tell the map maker to redo the map with the barriers z=0. Lets see if it works?

2020-11-07 11:21 UTC, Avyukt1 commented
Also a screenshot is required to use the map.

2020-11-08 19:17 UTC, Panquesito7 commented on plane_crash/map.conf
> +name = Plan Crash In Early December.Search for a tresure in your base.
```suggestion
name = Plan Crash In Early December. Search for a treasure in your base.
```

2020-11-09 09:23 UTC, JostP commented on plane_crash/map.conf
> +name = Plan Crash In Early December.Search for a tresure in your base.
`Search for a tresure in your base.` looks like a hint

2020-11-09 09:37 UTC, Avyukt1 requested changes
Instead of using the line:
`name = Plan Crash In Early December. Search for a treasure in your base.`
use
`name = Plane Crash In Early December.`
`hint = Search for a treasure in your base.`

2020-11-10 02:51 UTC, Sirius-Black4 commented
So is there a way i can edit the file using Github or do i have to edit the .conf file , correct it and re-upload it?

2020-11-10 03:10 UTC, Sirius-Black4 commented
Btw. who all are the people that have write access to merge pull requests?

2020-11-10 04:40 UTC, Avyukt1 commented
@JostP has the access to edit these file.

2020-11-11 13:44 UTC, Sirius-Black4 commented
I gess i will have too redo the whole map.

2020-11-11 13:46 UTC, Avyukt1 commented
Yes, If have not emerged the are.

2020-11-11 13:47 UTC, Sirius-Black4 commented
yes, i haven't emerged it properly. Btw how do i remove barriers because other wise il need to redo every thing.

2020-11-11 13:59 UTC, Avyukt1 commented
The steps of redoing the map are:
- Download the ctf_map modpack and the WorldEdit modpack.
- Create a new world with the these mods enabled.
- In the chat, do /gui and then click 'Player Pos'. Then click 'From We' and 'To We'.
- After that, choose z=0 and place the barriers.
- Then place the two flags.
- do /gui and in 'initial stuff' give at least a pickaxe. Or type 'default:pick_stone''
- Then type your username from the minetest ctf server as the author of the map.
- Then simply click export.
-  Take a screenshot of the map and host the files in this Pull Request.

2020-11-11 14:02 UTC, Avyukt1 commented
Remember.
Don't place the flags before placing the barrier.
The **_very fist_** thing is to emerge the area.
Go to https://minetest.rubenwardy.com/ctf for help.

2020-11-11 14:03 UTC, Avyukt1 commented
Follow the instructions and don't change the sequence of the list in the above message.
Do it step by step.

2020-11-12 09:18 UTC, Sirius-Black4 commented
You said that The very first thing is to emerge the area. Do you mean even before placing the barriers and just after making the world?

2020-11-12 10:58 UTC, Avyukt1 commented
Yes. True

2020-11-12 10:59 UTC, Avyukt1 commented
No
I am the very first thing.
Even before making the world

2020-11-12 15:48 UTC, Sirius-Black4 commented
Ok, i've redone the map , this is a whole new one and is very similar except it wont be in the chilly altitudes but more in a greenish mountain area.This time i've made it more fun by adding ores like iron , coal ,diamond and mese in concentrated areas in both sides of the team(equally).The mese and diamond will be found in your own base hidden,the iron will be in some ruins you will have to find.To make it even more fun i've also made a broken airplane crashed in the middle of the map.....and just wanted to know if i will have to make a new PR to get this one published?
Thanks for the support, ive learnt a lot :)  .

2020-11-13 05:19 UTC, Avyukt1 commented
@JostP 
Please take his files and add it to this Pull Request.

2020-11-13 05:23 UTC, Avyukt1 commented
> Ok, i've redone the map , this is a whole new one and is very similar except it wont be in the chilly altitudes but more in a greenish mountain area.This time i've made it more fun by adding ores like iron , coal ,diamond and mese in concentrated areas in both sides of the team(equally).The mese and diamond will be found in your own base hidden,the iron will be in some ruins you will have to find.To make it even more fun i've also made a broken airplane crashed in the middle of the map.....and just wanted to know if i will have to make a new PR to get this one published?
> Thanks for the support, i've learnt a lot :) .

@Sirius-Black4 
Make a new GitHub repository with these a the
`map.conf`
`map.mts`
and we need a screenshot of the map.
press F12 while flying to capture a screenshot.
add the screenshot.png file in your repository.
@JostP will make the changes.

2020-11-13 07:20 UTC, Sirius-Black4 commented
Ok ,can someone make a new PR for me idk how to make one, i have sent the screenshots and .zip in the forums.

2020-11-13 07:21 UTC, Avyukt1 commented
Share me the link please

2020-11-13 07:51 UTC, Sirius-Black4 commented
Link for what?
This is the link for the screenshots of the new map - https://postimg.cc/gallery/DhcdnY7

2020-11-13 07:52 UTC, Avyukt1 commented
Where are your files?

2020-11-13 07:53 UTC, Avyukt1 commented
We need the files for the new Pull Request

2020-11-13 07:57 UTC, Avyukt1 commented
At least tell me which topic for the minetest forums have you given the map .zip file?

2020-11-13 07:59 UTC, Sirius-Black4 commented
This is a whole new one and is very similar except it wont be in the chilly altitudes but more in a greenish mountain area.This time i've made it more fun by adding ores like iron , coal ,diamond and mese in concentrated areas in both sides of the team(equally).The mese and diamond will be found in your own base hidden,the iron will be in some ruins you will have to find.To make it even more fun i've also made a broken airplane crashed in the middle of the map.....and just wanted to know if i will have to make a new PR to get this one published?Screenshots can be viewed here - https://postimg.cc/gallery/DhcdnY7
Thanks for the support, ive learnt a lot :) .
© 2020. This work is licensed under a CC BY 4.0 license.
[PlaneCrashCTF.zip](https://github.com/MT-CTF/maps/files/5535462/PlaneCrashCTF.zip)

2020-11-13 08:06 UTC, Avyukt1 commented
@Sirius-Black4 
-You have placed the flags before placing the barrier.
-You have made a big mess.
-You also emerged the area after building.

2020-11-13 08:08 UTC, Sirius-Black4 commented
No, i haven't placed the flag before placing the barriers , and what do you mean i have made a big mess?

2020-11-13 08:10 UTC, Avyukt1 commented
The barriers are invisible while the barriers you placed are on the far off.
We also cannot get the items.

2020-11-13 08:11 UTC, Avyukt1 commented
It should be
`initial_stuff = default:pick_steel,default:torch 10`
instead of what you wrote.

2020-11-13 08:11 UTC, Sirius-Black4 commented
well i dont understand what do you mean the barriers are invisible, can you please send a screenshot.....

2020-11-13 08:13 UTC, Avyukt1 commented
> well i dont understand what do you mean the barriers are invisible, can you please send a screenshot.....
I can give you a video for that

2020-11-13 08:18 UTC, Sirius-Black4 commented
Yes can you send something so i can see how it looks for you.

2020-11-13 08:24 UTC, Avyukt1 commented
You can try testing it.
go to https://github.com/MT-CTF/capturetheflag/ to download the subgame.

2020-11-13 08:26 UTC, Avyukt1 commented
open http://www.filedropper.com/minetest530opengl4302020-11-1313-48-29
and download the video

2020-11-13 08:35 UTC, Sirius-Black4 commented
Thanks i get it, idk whats causing it to get you back to the base because i did every thing you told me to do except for merging it after placing barriers which i suppose **can not** be the reason for you going back to your base.

2020-11-13 08:49 UTC, Avyukt1 commented
> Thanks i get it, idk whats causing it to get you back to the base because i did every thing you told me to do except for merging it after placing barriers which i suppose **can not** be the reason for you going back to your base.

Yes, It happens.
But If you are in the other team. you can dig underground and cross the barrier.

2020-11-13 08:50 UTC, Avyukt1 commented
And Yes.
You have to merge the area even before building the place and placing barriers.

2020-11-13 08:53 UTC, Avyukt1 commented
Anyway,
I liked the map.
Good map for the server' Let @JostP test it.
Till then, you debug the map.
One more thing
I am `smugler5`

2020-11-13 09:05 UTC, Avyukt1 commented
I'll give you the video how to make the map.
It will tell you the proper sequence

2020-11-13 09:14 UTC, Sirius-Black4 commented
Thanks alot man, your a great help.

2020-11-13 10:05 UTC, Avyukt1 commented
You can see the tutorial at https://1drv.ms/v/s!AlEgFl9GC_oKiQUiX-Bhr83cmQPS?e=RaHspN

2020-11-13 10:33 UTC, Sirius-Black4 commented
Thanks alot, this is exactly what i did except i emerged it wrong.

2020-11-13 11:46 UTC, Avyukt1 commented
Redo the map a and give the files.
I'll create a new Pull Request

2020-11-28 16:45 UTC, xenonca commented on plane_crash/map.conf
> +name = Plan Crash In Early December. Search for a treasure in your base.
I think it was supposed to be `Plane Crash` right?
Also `Search for a treasure in your base` should be a `hint` I guess

2020-11-29 04:56 UTC, Avyukt1 requested changes

2020-12-15 10:00 UTC, Avyukt1 commented
@JostP  @xenonca 
Well, minetevc/[@Sirius-Black4 ](https://github.com/Sirius-Black4) is not online from a last few months. There are also bugs in this map. He hasn't fixed the bugs nor he has even been online in these day. We need to make the decision faster because other maps are still left for reviewing. I don't think we will get a reply for him. If we get, that's actually good, but if we don't we will have to temporarily close this PR.

2020-12-15 10:40 UTC, Sirius-Black4 commented
Hi well i am online mostly but i cant play often these days, i think i will be able to fix the bugs by this Friday or so. I will need to redo the whole map probable.

2020-12-15 11:05 UTC, JostP commented
I think there is an updated version on MT forum, I can update PR today

2020-12-16 04:02 UTC, Avyukt1 commented
@Sirius-Black4  Thanks a lot for coming and replying back ;)

2020-12-16 08:21 UTC, JostP commented
Updated.
@Avyukt1 you can test it if you want.

2020-12-16 13:25 UTC, JostP commented
Map is exported wrongly it is cutted at the borders
![Zaslonska slika 2020-12-16 14-11-57](https://user-images.githubusercontent.com/47271658/102353615-9a8eba00-3fa9-11eb-90d8-1e0ad5058e53.png)

2020-12-17 03:03 UTC, Avyukt1 commented
The barrier doesn't disappear and its not in the middle of the map.

2020-12-17 05:26 UTC, Avyukt1 requested changes

2020-12-17 05:26 UTC, Avyukt1 commented on plane_crash/map.conf
> +initial_stuff = default:pick:steel,default:torches:10
There is a bug in initial stuff.
```suggestion
initial_stuff = default:pick_steel,default_torch 10
```

2020-12-17 05:33 UTC, Avyukt1 commented
![bug](https://user-images.githubusercontent.com/65779812/102448107-6e317700-4057-11eb-99e8-5fb8e40338ba.gif)
Man, that barrier isn't working properly, I can noclip through it.

2020-12-29 04:36 UTC, Avyukt1 commented
@JostP I think the `WIP` label is needed.

2020-12-29 09:41 UTC, JostP commented
> @JostP I think the `WIP` label is needed.
> And, we should convert this into a draft.

yes, I will add WIP, but I don't think draft is needed.

2021-02-04 11:30 UTC, JostP commented
Will re-open as soon as map is updated.

2021-02-04 11:30 UTC, closed without merging

2021-02-04 12:41 UTC, Sirius-Black4 reviewed
> Will re-open as soon as map is updated.

Ok sure.