Add "Lava Puddles by smugler5"
MT-CTF/maps pull request #147
Opened 2020-11-07 01:13 UTC by Avyukt1

2020-11-07 01:20 UTC, Avyukt1 commented
My map now works with no technical errors. I fixed them all. But I just want you all to test and review my map.

2020-11-08 19:15 UTC, Panquesito7 requested changes
The directory name should be `lava_puddles`.

2020-11-08 19:15 UTC, Panquesito7 commented on Lava-Puddles-Map/map.conf
> +treasures = shooter:shotgun, default:pick_steel, default:pick_steel, default:dirt 70, default:stone 60
Incorrect, this should be `shooter_guns:shooter`.
```suggestion
treasures = shooter_guns:shotgun, default:pick_steel, default:pick_steel, default:dirt 70, default:stone 60
```

2020-11-08 19:15 UTC, Panquesito7 commented on Lava-Puddles-Map/map.conf
> +others = This map is full of puddles with lava. Also there are diamond hidden somewhere.
```suggestion
others = This map is full of puddles with lava. Also there is diamond hidden somewhere.
```

2020-11-08 19:15 UTC, Panquesito7 commented on Lava-Puddles-Map/README.md
> +I request the minetest ctf team to add this map to their server.
I don't think this is needed.

2020-11-08 19:15 UTC, Panquesito7 commented on Lava-Puddles-Map/map.conf
> +licence = CC BY-SA
What is the license version? Is it CC BY-SA 4.0 or is it 3.0?

2020-11-08 19:15 UTC, Panquesito7 commented on Lava-Puddles-Map/map.conf
> +licence = CC BY-SA
```suggestion
license = CC BY-SA
```

2020-11-09 04:46 UTC, Panquesito7 requested changes
I believe naming your directory `lava_puddles` would be better.

2020-11-09 04:47 UTC, Avyukt1 commented
Okay,
Thanks!
I am making the changes.

2020-11-09 04:48 UTC, Avyukt1 commented on Lava-Puddles-Map/map.conf
> +licence = CC BY-SA
Okay,
Thanks!
I am making the changes.

2020-11-09 05:28 UTC, Avyukt1 commented
It is showing an error while uploading the files.

2020-11-09 06:05 UTC, Avyukt1 commented
I have deleted the other files but I cannot add my files. It is showing error.

2020-11-09 06:38 UTC, Avyukt1 commented
I think I should initialize the repository again.

2020-11-09 06:38 UTC, closed without merging