"Lava Puddles" by smugler5
MT-CTF/maps pull request #148
Opened 2020-11-09 09:17 UTC by Avyukt1

Done with debugging the files. Now it is ready for testing.

2020-11-09 09:25 UTC, JostP commented on lava_puddles/map.conf
> +licence = CC BY-SA
license version?

2020-11-09 09:27 UTC, Avyukt1 commented on lava_puddles/map.conf
> +licence = CC BY-SA
Edited.

2020-11-09 13:43 UTC, Avyukt1 commented
So, did the testers test the map?

2020-11-09 13:50 UTC, Avyukt1 commented
This map has lots of lava,
![screenshot_20201109_191659](https://user-images.githubusercontent.com/65779812/98548993-3a2c9e80-22c0-11eb-9650-c46d843e3a5e.png)
This map also has a castle-like construction.
![screenshot_20201109_191931](https://user-images.githubusercontent.com/65779812/98549251-8677de80-22c0-11eb-8757-0e30f86cfd5c.png)
Diamond is hidden in a small hole that goes ender the ground.

2020-11-09 17:09 UTC, JostP commented
How much diamond and mese?

2020-11-10 06:50 UTC, Avyukt1 commented
There are only 12 diamond ores in the map.
Totally, the sum of diamond swords craft able is '6' only.

2020-11-10 06:51 UTC, Avyukt1 commented
> How much diamond and mese?

My map doesn't have mese.
This map only has 12 diamond crystals. Only 6 diamond swords can be crafted.

2020-11-10 07:03 UTC, JostP commented
I think you should add more. Also add mese. If there is only 6 diamond swords in-game that means only good players will get them and they will be impossible to be killed.

2020-11-10 07:09 UTC, Avyukt1 commented
Yes! You are right. But Ii had got a review from Elvis26 and winniepee0 that lots of mese and diamond is bad idea.

- Plains of the Past
- Plain Battle
- River Valley

These maps have the same quantity of mese and diamond.
Shall I remove the treasure instead?

2020-11-10 07:15 UTC, Avyukt1 commented
Anyway,
I was the latest exported data was not working.
I couldn't see anything in the map after editing the map.

2020-11-10 13:37 UTC, Avyukt1 commented
Anyway, please test the and confirm me.

2020-11-10 13:37 UTC, Avyukt1 commented
Anyway, please test the map.
And confirm me.

2020-11-11 04:55 UTC, Avyukt1 commented
Did you all like it?

2020-11-13 09:49 UTC, Avyukt1 commented
Did you like my map?

2020-11-25 16:53 UTC, Panquesito7 requested changes

2020-11-25 16:53 UTC, Panquesito7 commented on lava_puddles/map.conf
> +name = Lava Puddles by smugler5
Adding ` by smugler5` is not needed. `name` is the **map name**.  `author` is for **map creator's name**.

2020-11-26 04:22 UTC, Avyukt1 commented
@Panquesito7 did you test my map?

2020-11-26 04:38 UTC, Panquesito7 commented
> @Panquesito7 did you test my map?

No, I haven't tested it.

2020-11-27 07:17 UTC, Avyukt1 commented
> > @Panquesito7 did you test my map?
> 
> No, I haven't tested it.

When will you test it?

2020-11-30 15:51 UTC, Avyukt1 commented
@JostP Please test my map.

2020-12-03 07:29 UTC, Avyukt1 commented
@JostP 
I think you will not like any map made by me.
I had created this PR before other PRs and you tested other PRs before mine.
I don't think you'll test my map ever.
If I don't get a message before 5 days, I'll delete this Pull Request.

2020-12-03 12:47 UTC, winniepee commented
1. People have tested it, but you just need to wait for few months or so. 
2. If you delete this your map don't have a chance to get it.
3. Try making other maps. Make it special for the players so the map can merge it faster.

Hope you can be patient enough! :)

2020-12-04 07:40 UTC, Avyukt1 commented
> 1. People have tested it, but you just need to wait for few months or so.
okay!

2020-12-04 15:39 UTC, Avyukt1 commented
Bruh, I am angry on you @JostP 
you are very partial!

2020-12-04 15:39 UTC, closed without merging

2020-12-04 17:51 UTC, JostP commented
@Avyukt1 I don't agree with you.
First, I didn't merge any new map created after yours. Yeah, I merged some quick made PR for current maps fixes because the quality of merged maps is important. If you are impatient and can't wait few more days, do whatever you want, I can't help you. You can leave your PR opened, I don't understand why you closed it.

People are creating a lot of new maps recently what causes long waiting for new maps to be reviewed.
I can't dislike your map if as haven't even tested it yet and if I disliked your map, I would first ask other people if they likes it. From what I see, your map looks interesting especially because it has good ores such as mese and diamonds which make fun matches.

2020-12-05 02:53 UTC, Avyukt1 commented
> @Avyukt1 I don't agree with you.
> First, I didn't merge any new map created after yours. Yeah, I merged some quick made PR for current maps fixes because the quality of merged maps is important. If you are impatient and can't wait few more days, do whatever you want, I can't help you. You can leave your PR opened, I don't understand why you closed it.
> 
> People are creating a lot of new maps recently what causes long waiting for new maps to be reviewed.
> I can't dislike your map if as haven't even tested it yet and if I disliked your map, I would first ask other people if they like it. From what I see, your map looks interesting especially because it has good ores such as mese and diamonds which make fun matches.

@JostP 
This is what I call partiality or laziness!

2020-12-05 09:13 UTC, Avyukt1 commented
@JostP how much time does it take to test and review a map?

2020-12-05 09:14 UTC, JostP commented
more days because most of the maps are not created correctly and have many bugs

2020-12-05 09:15 UTC, Avyukt1 commented
> more days because most of the maps are not created correctly and have many bugs

Olliy, winniepee and Elvis26 tested it and they didn't find a bug.

2020-12-05 09:16 UTC, Avyukt1 commented
Reject my map if you don't even want to see it.