Two Volcanoes Map by Oliver4
MT-CTF/maps pull request #153
Opened 2020-11-19 10:14 UTC by AnyBlue

New map by Oliver4

2020-11-19 21:24 UTC, olliy1or commented
The map has no license

2020-11-20 07:01 UTC, AnyBlue commented
> The map has no license

I will ask him.

2020-12-09 09:57 UTC, Avyukt1 requested changes

2020-12-09 09:57 UTC, Avyukt1 commented on volcanoes/map.conf
> +initial_stuff = default:pick_steel,default:torch 10,shooter_guns:pistol
This gives an unloaded pistol,
```suggestion
initial_stuff = default:pick_steel,default:torch 10,shooter_guns:pistol_loaded
```

2020-12-09 10:05 UTC, Avyukt1 commented
This map doesn't have bugs. Also It has a good treasure. But the land flat and I think you should add more trees or mountains in the free space.

2020-12-17 08:16 UTC, olliy1or commented
imo the map is a little plain 
cant use the volcanoes for anything much
maybe add a little more builds to the sides and near the bases?

2020-12-17 13:06 UTC, JostP commented
Map works perfectly, but unfortunately it map won't be added:
- very plain, it isn't unique , we already have to many of them.
- we already have to many maps with good ores such as mese and diamond.

2020-12-17 13:07 UTC, closed without merging