Wall Of Wisdom by Fox/Whitzy
MT-CTF/maps pull request #177
Opened 2020-12-16 15:45 UTC by Fox3058

2020-12-16 16:19 UTC, AnyBlue commented
Please rename the Screenshot on screenshot

2020-12-22 10:53 UTC, Avyukt1 requested changes

2020-12-22 10:53 UTC, Avyukt1 commented on wall_of_wisdom/map.conf
> +initial_stuff = Default:cobble 50,default:torch 20,default:pick_steel
```suggestion
initial_stuff = default:cobble 50,default:torch 20,default:pick_steel
```
You shouldn't use capital letters else that will not give the correct item.

2020-12-22 10:55 UTC, Avyukt1 commented
This map is **too plain**. add more forest or other constructions.

This map is just like The Wall by Thomas-S

2021-02-03 13:01 UTC, JostP commented
re-open when you finish

2021-02-03 13:01 UTC, closed without merging