New Map for review "Abandoned Battlefield"
MT-CTF/maps pull request #183
Opened 2020-12-26 14:33 UTC by HobbitPower

Map for review.

* If it got accepted: Maybe we could add an hint: "There is a mine in each base. Battle tanks can be useful"
* There are 4 shelters in each base: At the right (if you look from the middle wall) is the base with the flag, 1 is closed (contains wood), 2 are open and empty. Maybe the chests could spawn in the empty ones.

2020-12-27 05:17 UTC, Panquesito7 reviewed
Screenshot looks pretty cool. 🙂

2020-12-31 17:25 UTC, Avyukt1 commented
I tested it and saw, this is very cool but its actually not that good one. But I liked it :wink:

2021-01-01 15:27 UTC, HobbitPower commented
> I tested it and saw, this is very cool but its actually not that good one. But I liked it 😉, better if you remove the mese & diamond and replace the dirt for those tunnels with something else.

Hey thx for the review. Mese? I just placed 4 diamond ore afaik xD And what do you mean with dirt in tunnels (?)
I probably have to re-upload the map anyway (False center)

2021-01-02 04:25 UTC, Avyukt1 commented
Yeah, I didn't see mese but I thought there was some in the mine. Anyway...

2021-01-03 09:28 UTC, AnyBlue commented
Add license please!

2021-01-03 09:29 UTC, AnyBlue requested changes
I recommend to add torches

2021-01-03 15:49 UTC, HobbitPower commented
> Add license please!

Done.

2021-01-03 15:54 UTC, HobbitPower commented
> I recommend to add torches

Where? Can you be more specific pls :D Imo the shelters got enough light (mese lamps, mese post lights). The rest of the map is indeed debatable, but other maps are dark in the night too ^^

2021-01-04 11:07 UTC, AnyBlue commented
> > I recommend to add torches
> 
> Where? Can you be more specific pls :D Imo the shelters got enough light (mese lamps, mese post lights). The rest of the map is indeed debatable, but other maps are dark in the night too ^^

In the initial_stuff.

2021-01-04 11:10 UTC, Avyukt1 commented on abandoned_battlefield/map.conf
> +initial_stuff = default:cobble 40, shooter:pistol, default:pick_steel
```suggestion
initial_stuff = default:cobble 40, shooter:pistol, default:pick_steel,default:torch 5
```

2021-01-04 11:17 UTC, AnyBlue commented on abandoned_battlefield/map.conf
> +initial_stuff = default:cobble 40, shooter:pistol, default:pick_steel
It's an unloaded pistol...
```suggestion
initial_stuff = default:cobble 40, shooter:pisto_loadedl, default:pick_steel
```

2021-01-04 15:31 UTC, HobbitPower commented
> > > I recommend to add torches
> > 
> > 
> > Where? Can you be more specific pls :D Imo the shelters got enough light (mese lamps, mese post lights). The rest of the map is indeed debatable, but other maps are dark in the night too ^^
> 
> In the initial_stuff.

Yeah sorry, i was dumb and tired xD thought you meant in the map itself.

2021-01-04 15:38 UTC, JostP commented on abandoned_battlefield/map.conf
> +initial_stuff = default:cobble 40, shooter:pistol, default:pick_steel, default:torch 5
```suggestion
initial_stuff = default:cobble 40,shooter:pistol,default:pick_steel,default:torch 5
```

Small fix, there shouldn't be spaces after comma otherwise initial stuff might not work correctly.

2021-01-12 12:18 UTC, JostP commented
Reviewed:
Very nice map and nice work with chest zones :+1:.

I didn't found any bugs, but there are 2 things:

- There is only 2 diamonds on each side of the map and I think the person who will have there 2 diamonds will be very powerful. I would suggest placing 2 meses instead as they are less OP. It is not a big issue, but I still think there could be problems. If you don't want to change, no problem, but we don't know what will happen in-game.
- A screenshot should have ratio 3:2. Use this one in your PR:
![screenshot](https://user-images.githubusercontent.com/47271658/104313548-75be3180-54d8-11eb-9235-b9bf4c4113a0.png)

2021-01-12 12:24 UTC, JostP commented on abandoned_battlefield/map.conf
> +hint = Bunkers/shelters and battle tanks can be useful.
```suggestion
hint = Find ores hidden on a secret place!
```
I would suggest this hint, modify it if you want. Hint for chest zones isn't needed IMO.

2021-01-12 19:32 UTC, Panquesito7 commented on abandoned_battlefield/map.conf
> +hint = Bunkers/shelters and battle tanks can be useful.
```suggestion
hint = Find hidden ores on a secret place!
```

2021-01-16 11:39 UTC, JostP approved these changes
Looks good, both issues fixed :+1:
Will merge after map voting, ~7-14 days.

2021-01-16 12:14 UTC, wwar-XeStro commented
Looks good, better than last added maps.

2021-01-17 20:14 UTC, Panquesito7 requested changes

2021-01-17 20:14 UTC, Panquesito7 commented on abandoned_battlefield/map.conf
> +
This line isn't needed, there's already an endline, but GitHub doesn't display it. 😉
```suggestion
```

2021-01-18 08:49 UTC, JostP commented on abandoned_battlefield/map.conf
> +hint = Find ores hidden on a secret place!
```suggestion
hint = Find hidden ores on a secret place!
```
One more trivial thing. This might sound better in English.

2021-01-19 06:00 UTC, Panquesito7 approved these changes
Didn't test, but everything looks good. 👍

2021-01-20 08:30 UTC, moreavy approved these changes
Map Working Fine!

2021-01-20 14:58 UTC, JostP approved these changes

2021-01-21 04:27 UTC, moreavy commented
@JostP `Two Approvals` label needed right?

2021-01-28 13:40 UTC, merged