Add New Map "Bunker"
MT-CTF/maps pull request #192
Opened 2021-01-13 15:58 UTC by Avyukt1

New map by realyg, winniepee0, smugler5, SoulSeeker & Darkf4antom!

2021-01-13 16:10 UTC, Avyukt1 commented
@JostP Will 👇🏾 can you create the blow image to `screenshot.png`?
![image](https://user-images.githubusercontent.com/65779812/104478077-d9835000-55e7-11eb-9c9d-45d6496bc150.png)

2021-01-14 00:15 UTC, KodaTheGuy commented
Look mom I made it!

2021-01-15 03:50 UTC, Panquesito7 reviewed
Shouldn't the folder name be `bunker_in_snow` or `bunker_in_the_snow`?

2021-01-15 03:50 UTC, Panquesito7 commented on bunker/map.conf
> +license = CC BY-SA 4.0 Thanks for j45 to host the server to create the map.
I think that text should be moved to somewhere else.
```suggestion
license = CC BY-SA 4.0
```

2021-01-15 03:50 UTC, Panquesito7 commented on bunker/map.conf
> +author = realyg,winniepee0,smugler5,Soulseeker,Darkf4antom and Tryhard_
```suggestion
author = realyg, winniepee0, smugler5, Soulseeker, Darkf4antom and Tryhard_
```

2021-01-15 05:43 UTC, Avyukt1 commented on bunker/map.conf
> +license = CC BY-SA 4.0 Thanks for j45 to host the server to create the map.
We want to give j45 some credits.

2021-01-15 06:02 UTC, Avyukt1 commented on bunker/map.conf
> +license = CC BY-SA 4.0 Thanks for j45 to host the server to create the map.
```suggestion
license = CC BY-SA 4.0
others = Thanks for j45 to host the server to create the map.
```

Will this work?

2021-01-15 10:08 UTC, JostP commented on bunker/map.conf
> +license = CC BY-SA 4.0 Thanks for j45 to host the server to create the map.
Yes, it should work. When you test, type /maps and select your map from the list.

2021-01-15 10:10 UTC, JostP commented on bunker/map.conf
> +license = CC BY-SA 4.0 Thanks for j45 to host the server to create the map.
Maybe `"Thanks to j45 ..."` would be better in English

2021-01-15 16:19 UTC, Avyukt1 commented
@Panquesito7 Done!

2021-01-17 20:18 UTC, Panquesito7 commented on bunker_in_the_snow/map.conf
> +others = Thanks to j45 for hosting the server to create the map.
Missing new line at the end.
```suggestion
others = Thanks to j45 for hosting the server to create the map.

```

2021-01-18 09:22 UTC, Avyukt1 commented on bunker_in_the_snow/map.conf
> +others = Thanks to j45 for hosting the server to create the map.
That happens when you click `edit`. No need for that

2021-01-18 20:36 UTC, Panquesito7 commented on bunker_in_the_snow/map.conf
> +others = Thanks to j45 for hosting the server to create the map.
It's better to add  it as some IDE's have the end of line set to `lf`, so it's better to add an endline to avoid issues.

2021-01-19 03:25 UTC, Avyukt1 commented on bunker_in_the_snow/map.conf
> +others = Thanks to j45 for hosting the server to create the map.
What do you exactly mean?

2021-01-19 06:01 UTC, Panquesito7 commented on bunker_in_the_snow/map.conf
> +others = Thanks to j45 for hosting the server to create the map.
It's always good to add an endline.

2021-01-19 06:03 UTC, Avyukt1 commented on bunker_in_the_snow/map.conf
> +others = Thanks to j45 for hosting the server to create the map.
what is endline?

2021-01-19 06:07 UTC, Panquesito7 commented on bunker_in_the_snow/map.conf
> +others = Thanks to j45 for hosting the server to create the map.
> what is endline?

_Offtopic_: A new line at the end of the file or an empty line.

2021-01-19 07:30 UTC, Avyukt1 commented on bunker_in_the_snow/map.conf
> +others = Thanks to j45 for hosting the server to create the map.
Already committed!

2021-01-19 18:43 UTC, Panquesito7 approved these changes
Didn't test, but everything looks good. 👍

2021-01-20 08:29 UTC, moreavy commented
@JostP The `One Approval` label can be added here.

2021-01-20 09:52 UTC, JostP commented
> @JostP The `One Approval` label can be added here?

Not yet, Panquesito7's approval didn't test map

2021-01-22 14:59 UTC, moreavy commented
I am Adding Skybox images tomorrow.

2021-01-27 05:42 UTC, Panquesito7 commented on bunker_in_the_snow/map.conf
> +initial_stuff = default:pick_stone,default:torch 10,shooter_guns:pistol_loaded
`pistol` and `pistol_loaded` both work fine, but `pistol` is better IMO.
```suggestion
initial_stuff = default:pick_stone,default:torch 10,shooter_guns:pistol
```

2021-01-27 05:44 UTC, moreavy commented on bunker_in_the_snow/map.conf
> +initial_stuff = default:pick_stone,default:torch 10,shooter_guns:pistol_loaded
**No!** `shooter_guns:pistol` is unloaded pistol. I have tested it in many map tests and ik the output given to me.

2021-01-27 18:17 UTC, Panquesito7 commented on bunker_in_the_snow/map.conf
> +initial_stuff = default:pick_stone,default:torch 10,shooter_guns:pistol_loaded
https://github.com/MT-CTF/maps/pull/194#discussion_r563490287

2021-01-28 06:09 UTC, moreavy commented on bunker_in_the_snow/map.conf
> +initial_stuff = default:pick_stone,default:torch 10,shooter_guns:pistol_loaded
Even this works fine...

2021-01-29 14:52 UTC, moreavy commented on bunker_in_the_snow/map.conf
> +author = realyg, winniepee0, smugler5, Soulseeker, Darkf4antom and Tryhard_
```suggestion
author = realyg, winniepee0, -sniper-, smugler5, Soulseeker, Darkf4antom and Tryhard_
```

2021-01-29 15:50 UTC, JostP commented on bunker_in_the_snow/map.conf
> +author = realyg, winniepee0, smugler5, Soulseeker, Darkf4antom and Tryhard_
Let me finish my improvements first ;)

2021-01-30 13:53 UTC, JostP approved these changes

2021-01-30 14:28 UTC, MoreKat commented
Very boring and plain map. Basically completely flat apart from two ugly giant stonebrick cubes (the bunkers) in front of the bases. The only slightly interesting part about this map is the underground tunnel system. Those tunnels certainly come in handy to get the flag because above ground there is barely any cover.

2021-01-30 15:14 UTC, moreavy commented
> Very boring and plain map. Basically completely flat apart from two ugly giant stonebrick cubes (the bunkers) in front of the bases. The only slightly interesting part about this map is the underground tunnel system. Those tunnels certainly come in handy to get the flag because above ground there is barely any cover.

What changes should be made?

2021-01-30 16:35 UTC, sodomite commented
Remove unbreakable nodes, it would be boring with them.

2021-01-30 17:19 UTC, JostP commented
> Remove unbreakable nodes, it would be boring with them.

good idea actually

2021-02-01 01:14 UTC, Panquesito7 requested changes
Why is the screenshot in the root directory? It should be in the `bunkers` directory.

2021-02-02 14:18 UTC, JostP approved these changes

2021-02-02 19:24 UTC, Panquesito7 approved these changes
Map seems to be working fine, looks cool, though in some parts of the map there are unbreakable and breakable nodes of the same type very closely.

2021-02-09 13:03 UTC, JostP commented
Merging, if map show itself as unpopular, we will remove it before map voting. I think it won't be unpopular tho. It shouldn't be hard to take flag so I think we won't have long matches on this map.

2021-02-09 13:05 UTC, merged