Moon: increase gravity a little
MT-CTF/maps pull request #206
Opened 2021-02-13 18:31 UTC by JostP

2021-02-14 02:36 UTC, Panquesito7 reviewed
I've tested it; to be honest, it isn't as fun as it was before. Maybe decrease a little bit the gravity?

2021-02-14 05:52 UTC, moreavy reviewed
Maybe adding torches in `initial_stuff` would be a good idea though.

2021-02-14 05:52 UTC, moreavy commented on moon/map.conf
>  initial_stuff = default:shovel_steel,shooter:pistol
```suggestion
initial_stuff = default:shovel_steel,shooter:pistol,default:torch 3
```

2021-02-14 06:17 UTC, moreavy commented
I suggest the `decision needed ⚖️` label can be used here as @Panquesito7 and @moreavy have tested and it works fine. But what we need is just a final decision right now or maybe a change the the moon's `map.conf` file.

2021-02-14 09:56 UTC, JostP commented
> I've tested it; to be honest, it isn't as fun as it was before. Maybe decrease a little bit the gravity?

Thanks for testing. Yes, we haven't decided if this will be merged, that's why we need many people to tell their opinion.

2021-02-14 15:57 UTC, olliy1or approved these changes

2021-02-17 07:26 UTC, moreavy requested changes
Not as fun as the old moon. Less Gravity makes the moon realistic. I didn't like the increased gravity of the moon.

2021-02-17 14:40 UTC, MoreKat reviewed
Tested it and I wouldn't change it. The reduced gravity is what makes the map unique, and I don't think this would have a significant impact on people's opinion about the map.

2021-02-17 15:26 UTC, Toby1710 approved these changes

2021-02-17 22:41 UTC, Panquesito7 commented
> Maybe adding torches in `initial_stuff` would be a good idea though.

This should be made in another PR.

2021-02-19 11:59 UTC, JostP commented
Will deal with this later.
I have some plans to improve moon map one day, currently it has some issues, on of them long matches.

2021-02-19 11:59 UTC, closed without merging