Add "Coral Reef" by -lipop-
MT-CTF/maps pull request #207
Opened 2021-02-14 17:44 UTC by moreavy

New Map made by -lipop-

2021-02-14 20:58 UTC, Panquesito7 commented on coral_reef/map.conf
> +initial_stuff = default:cobble 99
You should probably add 3 torches or more.

2021-02-14 21:03 UTC, Panquesito7 commented on coral_reef/map.conf
> +initial_stuff = default:cobble 99
Please include a pickaxe (at least a stone pickaxe).

2021-02-14 21:08 UTC, Panquesito7 reviewed
Tested; no bugs found. But, there's too much water, players won't be able to PvP properly, the map is practically all water. Maybe add somewhere players can stand and PvP a bit (not sure if it's a good idea though).

2021-02-19 20:06 UTC, Panquesito7 reviewed
From the screenshot, it looks cool. 👍

2021-02-20 08:15 UTC, moreavy reviewed
When I tested, I didn't find any bug. But I found other water without the constructions very normal leaving the cliff over there. The map can be done better if the author adds more constructions.

2021-02-20 14:41 UTC, JostP commented
Still WIP or already finished?

2021-02-20 14:46 UTC, moreavy commented
> Still WIP or already finished?

Its finished according to -lipop-

2021-02-21 01:52 UTC, Panquesito7 commented on coral_reef/map.conf
> +initial_stuff = default:pick_stone,default:torch 3,default:cobble 99,
```suggestion
initial_stuff = default:pick_stone,default:torch 3,default:cobble 99
```

2021-02-21 04:38 UTC, Panquesito7 approved these changes
Tested, no bugs found. The map looks cool; players will be able to PvP easier than before.
The only thing is the color of the wool in the blue base, it should be blue, not red (not sure if this is a good idea).

2021-03-03 07:01 UTC, moreavy commented
-lipop- made changes, I just need to update the screenshot.

2021-03-07 14:53 UTC, RyanZem reviewed
I didn't review the map yet but I can see that you need to add yet some buildings or bridges.
This map looks nice, the bridge is nice too, but I can see that snipers can shoot in base. 
You can add a wall near the bases and snipers won't spawn-kill.

2021-03-14 10:13 UTC, moreavy commented
@RyanZem Done!

2021-03-15 13:44 UTC, moreavy commented
This map is flat and similar to Thomas-S's map, -lipop- told me to close this.

2021-04-06 09:48 UTC, HobbitPower reviewed
Hm, i am torn between approval and refusal. 
Nice buildings (like the corals, base etc) but it looks a bit "thrown together". Also all fights will mostly take place at the middle glass path. 
Quite similiar to the Big Ocean map (although Big Ocean even has skybridges/walks).
I like the positions of the chests.

2021-04-09 07:39 UTC, DiamondPlane reviewed
I think this map has too much unbreakable things... Almost everything that I wanted to dig is just unbreakable. It's hard to capture, I see... I think you should make at least the glass or wool around base breakable, plus I think it's similar to Big Ocean, like HobbitPower said. Also, you should update the screenshot. There are many things that are not on the screenshot.
But this map looks good for me, buildings are cool.
This is my review.

2021-04-25 09:11 UTC, MoreKat requested changes
First of all, too similar to Big Ocean; an ocean with a bridge going from one base to the other and some random buildings on the sides. Something that I also notice is that the map lacks coherence: looks like a bunch of random, individual buildings were put together without respecting a general theme. For example, on one side of the map you have these realistic looking boats and on the other side cartoon sea creatures. The seemingly wrong proportions also add to this impression, e.g. the dolphin that's bigger than the boat. 

Another issue that I see is that capturing might be hard. Base is surrounded by shallow water, in which you can see an enemy coming from far away. Especially blue is at a disadvantage because there are cliffs next to their base, connected to the skybridge, which red can use to capture easily. There is no such thing on red's side.

2022-03-13 08:51 UTC, closed without merging